services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: gestion_telefonica
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=gestion_telefonica
      - DB_USER=root
      - DB_PASSWORD=
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: npm start
    depends_on:
      - backend

volumes:
  db_data:
