# Generated by Django 5.2.1 on 2025-05-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('siglas_facultad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorTelefono',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('siglas_proveedor', models.CharField(max_length=10)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('costo_seg_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_sim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_idi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depto', models.CharField(max_length=100)),
                ('siglas_depto', models.CharField(max_length=10)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='CalculaMensual',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('tarif_generales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_sin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_idi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_anexo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('encargado', 'Encargado de Unidad')], max_length=20)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedortelefono')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlamadas',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_llamada_sigla', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('fecha_llamada', models.DateField()),
                ('hora_llamada', models.TimeField()),
                ('tipo_respuesta', models.CharField(max_length=50)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('id_anexo', models.ForeignKey(db_column='id_anexo', on_delete=django.db.models.deletion.CASCADE, to='core.anexo')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedortelefono')),
            ],
        ),
    ]
