# Generated by Django 5.2 on 2025-06-08 17:55

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('siglas_facultad', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cuenta_presupuestaria',
            },
        ),
        migrations.CreateModel(
            name='ProveedorTelefono',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('siglas_proveedor', models.CharField(max_length=10)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('costo_seg_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_slm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_ldi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depto', models.CharField(max_length=100)),
                ('siglas_depto', models.CharField(max_length=10)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='CalculoMensualGeneral',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calculo', models.CharField(max_length=60)),
                ('duracion_total', models.IntegerField()),
                ('duracion_slm', models.IntegerField()),
                ('duracion_cel', models.IntegerField()),
                ('duracion_ldi', models.IntegerField()),
                ('tarif_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_slm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_ldi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
            options={
                'db_table': 'calculo_general',
            },
        ),
        migrations.CreateModel(
            name='CalculoMensualDepto',
            fields=[
                ('id_calculo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_calculo', models.CharField(max_length=60)),
                ('duracion_total', models.IntegerField()),
                ('duracion_slm', models.IntegerField()),
                ('duracion_cel', models.IntegerField()),
                ('duracion_ldi', models.IntegerField()),
                ('tarif_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_slm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_ldi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
            options={
                'db_table': 'calculo_mensual',
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_anexo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='anexos/', validators=[core.models.validar_excel])),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
            options={
                'db_table': 'anexos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('s_nombre', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=50)),
                ('apellido_m', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('encargado', 'Encargado de Unidad')], max_length=20)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='facultad',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedortelefono'),
        ),
        migrations.CreateModel(
            name='RegistroLlamadas',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_llamada_sigla', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('fecha_llamada', models.DateField()),
                ('hora_llamada', models.TimeField()),
                ('duracion_llamada', models.IntegerField(default=60)),
                ('tipo_respuesta', models.CharField(max_length=50)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('id_anexo', models.ForeignKey(db_column='id_anexo', on_delete=django.db.models.deletion.CASCADE, to='core.anexo')),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='core.proveedortelefono')),
                ('id_unidad', models.ForeignKey(db_column='id_unidad', on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'db_table': 'registro_llamadas',
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='reportes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
            options={
                'db_table': 'reportes_generados',
            },
        ),
    ]
