# Generated by Django 5.2 on 2025-05-03 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorTelefono',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo_seg_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_sim', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_seg_idi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_depto', models.CharField(max_length=100)),
                ('siglas_depto', models.CharField(max_length=10)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='CalculaMensual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tarif_generales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_sin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_cel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_idi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('nombre_depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id_anexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_anexo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('id_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPresupuestaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_facultad', models.CharField(max_length=100)),
                ('siglas_facultad', models.CharField(max_length=10)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedortelefono')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlamadas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('tipo_llamada_sigla', models.CharField(max_length=10)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('fecha_llamada', models.DateField()),
                ('hora_llamada', models.TimeField()),
                ('tipo_respuesta', models.CharField(max_length=50)),
                ('siglas_facultad', models.CharField(max_length=10)),
                ('siglas_unidad', models.CharField(max_length=10)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('id_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.anexo')),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultad')),
            ],
        ),
    ]
